services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'users_db'
      MYSQL_USER: 'user1'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'